name: Taraftarium24 Kanal Güncelleyici

on:
  schedule:
    # Her 6 saatte bir otomatik çalışır
    - cron: '0 */6 * * *'
  workflow_dispatch: # GitHub üzerinden manuel başlatma butonu ekler

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repoyu Klonla
      uses: actions/checkout@v3

    - name: Python Ortamını Kur
      uses: actions/setup-python@v4
      with:
        python-python-version: '3.x'

    - name: Kanal Çekme Betiğini Çalıştır
      run: python update_list.py

    - name: Değişiklikleri Kaydet ve GitHub'a Push Et
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add kanallar.m3u8
        git diff-index --quiet HEAD || git commit -m "Güncel kanallar eklendi [bot]"
        git push
