name: Taraftarium Kanal Güncelleyici

on:
  schedule:
    # Her 4 saatte bir otomatik çalışır
    - cron: '0 */4 * * *'
  workflow_dispatch: # GitHub arayüzünden manuel tetikleme butonu ekler

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repoyu Klonla
      uses: actions/checkout@v3

    - name: Python Ortamını Kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Kanal Çekme Betiğini Çalıştır
      run: python update_list.py

    - name: Değişiklikleri Git ile Push Et
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action Bot"
        git add kanallar.m3u8
        git diff-index --quiet HEAD || git commit -m "kanallar.m3u8 güncellendi [otomatik]"
        git push
